---
- name: Make Tenant dm-ansible1
  hosts: apics
  connection: local
  gather_facts: false
  
  vars:
    status: present

  vars_files:
    - external_vars.yml

  tasks:
    - name:  Creating Tenant
      cisco.aci.aci_tenant:
        tenant:           "{{ tenant_name }}"
        description:      "{{ aci_username }} created {{ tenant_name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Creating VRF
      cisco.aci.aci_vrf:
        tenant:           "{{ tenant_name }}"
        vrf_name:         "{{ vrf_name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"


    - name: Creating BD
      cisco.aci.aci_bd:
        tenant:           "{{ tenant_name }}"
        vrf_name:         "{{ vrf_name }}"
        bd:               "{{ bdname }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create a subnet
      cisco.aci.aci_bd_subnet:
        tenant:           "{{ tenant_name }}"
        bd:               "{{ bd.name }}"
        gateway:          "{{ bd.ip }}"
        mask:             "{{ bd.mask }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create AP
      cisco.aci.aci_ap:
        app_profile_name: "{{ app_profile_name }}"
        tenant:           "{{ tenant_name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create web_epg
      cisco.aci.aci_epg:
        tenant:           "{{ tenant_name }}"
        app_profile_name: "{{ app_profile_name }}"
        epg_name:         "{{ epg_name1 }}"
        bd_name:          "{{ bd.name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create web_epg contract
      cisco.aci.aci_epg_to_contract:
        tenant:           "{{ tenant_name }}"
        app_profile_name: "{{ app_profile_name }}"
        epg_name:         "{{ epg_name1 }}"
        contract:         "{{ contract_name }}"
        contract_type:    provider
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create db_epg
      cisco.aci.aci_epg:
        tenant:           "{{ tenant_name }}"
        app_profile_name: "{{ app_profile_name }}"
        epg_name:         "{{ epg_name2 }}"
        bd_name:          "{{ bd.name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create web_epg contract
      cisco.aci.aci_epg_to_contract:
        tenant:           "{{ tenant_name }}"
        app_profile_name: "{{ app_profile_name }}"
        epg_name:         "{{ epg_name2 }}"
        contract:         "{{ contract_name }}"
        contract_type:        provider
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create a Filter
      cisco.aci.aci_filter:
        filter_name:      "{{ filter_name }}"
        tenant:           "{{ tenant_name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name: Create Filter Entry
      cisco.aci.aci_filter_entry:
        filter_name:      "{{ filter_name }}"
        filter_entry:     "{{ entry_name }}"
        tenant:           "{{ tenant_name }}"
        ether_type:           unspecified
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name:  Create a Tenant Contract
      cisco.aci.aci_contract:
        tenant:           "{{ tenant_name }}"
        contract_name:    "{{ contract_name }}"
        scope:                tenant
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name:  Create Contract Subjects
      cisco.aci.aci_contract_subject:
        subject_name:     "{{ subject_name }}"
        contract_name:    "{{ contract_name }}"
        tenant:           "{{ tenant_name }}"
        reverse_filter:       yes
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name:  Bind Subject to filter
      cisco.aci.aci_contract_subject_to_filter:
        subject_name:     "{{ subject_name }}"
        contract_name:    "{{ contract_name }}"
        tenant:           "{{ tenant_name }}"
        filter_name:      "{{ filter_name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

    - name:  VMM Binding to EPGs
      cisco.aci.aci_epg_to_domain:
        app_profile_name: "{{ app_profile_name }}"
        tenant:           "{{ tenant_name }}"
        epg_name:         "{{ item }}"
        domain_type:          vmm
        vm_provider:          vmware
        domain_profile:   "{{ vmm_domain }}"
        deploy_immediacy:     immediate
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
        state:            "{{ status }}"

## Eample of a variables as a list
      with_items:
          - "{{ epg_name1 }}"
          - "{{ epg_name2 }}"

# Modified by damcfarl
#
# Usage:  sudo ansible-playbook -i hosts create_tenant.yml  -vvv
#
#  docs.ansible.com is essential to make sure you got the modules right
# variables are defined in exernal_vars.yml
