---
- name: Make Tenant dm-ansible1
  hosts: apics
  connection: local
  gather_facts: false
  
  vars:
    status: "absent"
    use_ssl: no

  vars_files:
    - external_vars.yml

  tasks:
    - name:  Remove Tenant
      cisco.aci.aci_tenant:
        tenant:           "{{ tenant_name }}"
        description:      "{{ aci_username }} created {{ tenant_name }}"
        host:             "{{ remote_device }}"
        username:         "{{ aci_username }}"
        password:         "{{ aci_password }}"
        validate_certs:   "{{ validate_certs }}"
#       state:            absent
#       ukn:
        state:            "{{ status }}"
#     delegate_to:        "{{ remote_device }}"

