name: "Ansible_WorkFlow"

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-connectivity:
   runs-on: self-hosted
   steps: 
      - run: |
          ping -c 2 10.88.36.23 
          
  validate-playbooks:
    needs: check-connectivity
    runs-on: self-hosted  
    steps: 
      - uses: actions/checkout@v3
      - run: |
          cd ansible/aci_tenants
          ansible-playbook -i hosts delete_tenant.yml -vvv -check
          
  deploy-playbooks:
    needs: [check-connectivity, validate-playbooks]
    runs-on: self-hosted
    
    steps: 
      - uses: actions/checkout@v3
      - run: |
          cd ansible/aci_tenants
          ansible-playbook -i hosts delete_tenant.yml -vvv
          
