name: Run playbook
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: create_tenant.yml
          directory: git_examples/ansible/aci_tenants
          options: |
            --inventory hosts
            --verbose
      - run: npm install -g bats
